services:
  ros2:
    image: ros2-turtlebot3
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_turtlebot3
    privileged: true
    network_mode: host
    ipc: host
    tty: true

    command: >
      /bin/bash -c '
        if [ -z "$$GOOGLE_API_KEY" ]; then
          echo "GOOGLE_API_KEY is not set.";
          exit 1;
        fi;
        exec bash;
      '

    volumes:
      - ../ros2_ws:/home/ubuntu/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

  ros2-gpu:
    extends: ros2
    container_name: ros2_turtlebot3_gpu
    profiles: ["gpu"]
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
